openapi: 3.0.0
info:
  title: Admin Panel API
  version: 1.0.0
paths:
  /admin/products:
    post:
      summary: Добавить новый товар
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
                categories:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Продукт добавлен
          
  /admin/products/{id}:
    delete:
      summary: Удалить товар по ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID товара
      responses:
        '204':
          description: Продукт удален
